--------------------------------------------------------
--  ������ ������ - ȭ����-8��-08-2023   
--------------------------------------------------------
DROP TABLE "MOVIEJD"."MEMBER_TBL" cascade constraints;
DROP TABLE "MOVIEJD"."NOTICE_TBL" cascade constraints;
--------------------------------------------------------
--  DDL for Table MEMBER_TBL
--------------------------------------------------------

  CREATE TABLE "MOVIEJD"."MEMBER_TBL" 
   (	"MEMBER_ID" VARCHAR2(20 BYTE), 
	"MEMBER_PW" VARCHAR2(30 BYTE), 
	"MEMBER_NAME" VARCHAR2(30 BYTE), 
	"MEMBER_GENDER" VARCHAR2(6 BYTE), 
	"MEMBER_EMAIL" VARCHAR2(50 BYTE), 
	"MEMBER_NICKNAME" VARCHAR2(20 BYTE), 
	"MEMBER_DATE" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"MEMBER_YN" VARCHAR2(1 BYTE) DEFAULT 'Y'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table NOTICE_TBL
--------------------------------------------------------

  CREATE TABLE "MOVIEJD"."NOTICE_TBL" 
   (	"NOTICE_NO" NUMBER, 
	"NOTICE_SUBJECT" VARCHAR2(50 BYTE), 
	"NOTICE_CONTENT" VARCHAR2(1000 BYTE), 
	"NOTICE_WRITER" VARCHAR2(50 BYTE), 
	"NOTICE_DATE" DATE DEFAULT SYSDATE, 
	"VIEW_COUNT" NUMBER DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
  
REM INSERTING into MOVIEJD.MEMBER_TBL
SET DEFINE OFF;
Insert into MOVIEJD.MEMBER_TBL (MEMBER_ID,MEMBER_PW,MEMBER_NAME,MEMBER_GENDER,MEMBER_EMAIL,MEMBER_NICKNAME,MEMBER_DATE,MEMBER_YN) values ('khuser01','pass01','�Ͽ���','M','khuser09@naver.com','�Ͽ����Դϴ�',to_timestamp('23/07/31 16:09:13.092000000','RR/MM/DD HH24:MI:SSXFF'),'Y');
Insert into MOVIEJD.MEMBER_TBL (MEMBER_ID,MEMBER_PW,MEMBER_NAME,MEMBER_GENDER,MEMBER_EMAIL,MEMBER_NICKNAME,MEMBER_DATE,MEMBER_YN) values ('khuser03','pass03','�����','M','khuser03@naver.com','�Ͽ���ģ��',to_timestamp('23/07/31 21:56:10.305000000','RR/MM/DD HH24:MI:SSXFF'),'Y');
Insert into MOVIEJD.MEMBER_TBL (MEMBER_ID,MEMBER_PW,MEMBER_NAME,MEMBER_GENDER,MEMBER_EMAIL,MEMBER_NICKNAME,MEMBER_DATE,MEMBER_YN) values ('khuser88','pass88','���ȿ���','M','khuser88@naver.com','���ȿ���',to_timestamp('23/08/07 15:05:17.187000000','RR/MM/DD HH24:MI:SSXFF'),'Y');
REM INSERTING into MOVIEJD.NOTICE_TBL
SET DEFINE OFF;
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (1,'��������','
 ù��° ���������Դϴ�~','admin',to_date('23/08/01','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (5,'�������� �ι�°',' 
�ι�° ���������Դϴ�.','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (12,'��������6��°','6��° ��������~~','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (13,'��������7��°','7��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (14,'��������8��°','8��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (15,'��������9��°','9��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (16,'��������10��°','10��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (17,'��������11��°','11��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (18,'��������12��°','12��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (19,'��������13��°','13��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (20,'��������14��°','14��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (21,'��������15��°','15��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (22,'��������16��°','16��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (23,'��������17��°','17��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (24,'��������18��°','18��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (25,'��������19��°','19��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (26,'��������20��°','20��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (27,'��������21��°','21��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (28,'��������22��°','22��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (29,'��������23��°','23��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (30,'��������24��°','24��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (31,'��������25��°','25��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (32,'��������26��°','26��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (33,'��������27��°','27��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (34,'��������28��°','28��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (35,'��������29��°','29��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (36,'��������30��°','30��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (37,'��������31��°','31��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (38,'��������32��°','32��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (39,'��������33��°','33��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (40,'��������34��°','34��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (41,'��������35��°','35��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (42,'��������36��°','36��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (43,'��������37��°','37��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (44,'��������38��°','38��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (45,'��������39��°','39��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (46,'��������40��°','40��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (47,'��������41��°','41��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (48,'��������42��°','42��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (49,'��������43��°','43��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (50,'��������44��°','44��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (51,'��������45��°','45��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (52,'��������46��°','46��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (53,'��������47��°','47��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (54,'��������48��°','48��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (55,'��������49��°','49��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (56,'��������50��°','50��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (57,'��������51��°','51��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (58,'��������52��°','52��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (59,'��������53��°','53��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (60,'��������54��°','54��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (61,'��������55��°','55��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (62,'��������56��°','56��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (63,'��������57��°','57��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (64,'��������58��°','58��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (65,'��������59��°','59��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (66,'��������60��°','60��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (67,'��������61��°','61��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (68,'��������62��°','62��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (69,'��������63��°','63��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (70,'��������64��°','64��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (71,'��������65��°','65��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (72,'��������66��°','66��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (73,'��������67��°','67��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (74,'��������68��°','68��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (75,'��������69��°','69��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (76,'��������70��°','70��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (77,'��������71��°','71��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (78,'��������72��°','72��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (79,'��������73��°','73��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (80,'��������74��°','74��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (81,'��������75��°','75��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (82,'��������76��°','76��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (83,'��������77��°','77��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (84,'��������78��°','78��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (85,'��������79��°','79��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (86,'��������80��°','80��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (87,'��������81��°','81��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (88,'��������82��°','82��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (89,'��������83��°','83��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (90,'��������84��°','84��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (91,'��������85��°','85��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (92,'��������86��°','86��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (93,'��������87��°','87��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (94,'��������88��°','88��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (95,'��������89��°','89��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (96,'��������90��°','90��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (97,'��������91��°','91��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (98,'��������92��°','92��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (99,'��������93��°','93��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (100,'��������94��°','94��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (101,'��������95��°','95��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (102,'��������96��°','96��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (103,'��������97��°','97��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (104,'��������98��°','98��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (105,'��������99��°','99��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (107,'��������101��°','101��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (108,'��������102��°','102��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (109,'��������103��°','103��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (110,'��������104��°','104��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (111,'��������105��°','105��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (112,'��������106��°','106��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (113,'��������107��°','107��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (114,'��������108��°','108��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (115,'��������109��°','109��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (116,'��������110��°','110��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (117,'��������111��°','111��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (118,'��������112��°','112��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (119,'��������113��°','113��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (120,'��������114��°','114��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (121,'��������115��°','115��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (122,'��������116��°','116��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (123,'��������117��°','117��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (124,'��������118��°','118��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (125,'��������119��°','119��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (126,'��������120��°','120��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (127,'��������121��°','121��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (128,'��������122��°','122��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (129,'��������123��°','123��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (130,'��������124��°','124��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (131,'��������125��°','125��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (132,'��������126��°','126��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (133,'��������127��°','127��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (134,'��������128��°','128��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (135,'��������129��°','129��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (136,'��������130��°','130��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (137,'��������131��°','131��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (138,'��������132��°','132��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (139,'��������133��°','133��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (140,'��������134��°','134��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (141,'��������135��°','135��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (142,'��������136��°','136��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (143,'��������137��°','137��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (144,'��������138��°','138��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (145,'��������139��°','139��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (146,'��������140��°','140��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (147,'��������141��°','141��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (148,'��������142��°','142��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (149,'��������143��°','143��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (150,'��������144��°','144��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (151,'��������145��°','145��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (152,'��������146��°','146��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (153,'��������147��°','147��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (154,'��������148��°','148��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (155,'��������149��°','149��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (156,'��������150��°','150��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (157,'��������151��°','151��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (158,'��������152��°','152��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (159,'��������153��°','153��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (160,'��������154��°','154��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (161,'��������155��°','155��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (162,'��������156��°','156��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (163,'��������157��°','157��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (164,'��������158��°','158��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (221,'200��° ��������','���̿�','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (166,'��������160��°','160��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (167,'��������161��°','161��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (168,'��������162��°','162��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (169,'��������163��°','163��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (170,'��������164��°','164��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (171,'��������165��°','165��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (173,'��������167��°','167��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (174,'��������168��°','168��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (175,'��������169��°','169��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (176,'��������170��°','170��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (177,'��������171��°','171��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (178,'��������172��°','172��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (179,'��������173��°','173��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (180,'��������174��°','174��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (181,'��������175��°','175��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (182,'��������176��°','176��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (183,'��������177��°','177��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (184,'��������178��°','178��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (185,'��������179��°','179��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (186,'��������180��°','180��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (187,'��������181��°','181��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (188,'��������182��°','182��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (189,'��������183��°','183��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (190,'��������184��°','184��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (192,'��������186��°','186��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (193,'��������187��°','187��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (194,'��������188��°','188��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (195,'��������189��°','189��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (196,'��������190��°','190��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (197,'��������191��°','191��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (198,'��������192��°','192��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (199,'��������193��°','193��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (200,'��������194��°','194��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (201,'��������195��°','195��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (202,'��������196��°','196��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (203,'��������197��°','197��° ��������','admin',to_date('23/08/02','RR/MM/DD'),0);
Insert into MOVIEJD.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (204,'��������198��°','198��° ��������~~~','admin',to_date('23/08/02','RR/MM/DD'),0);
--------------------------------------------------------
--  DDL for Index SYS_C007015
--------------------------------------------------------

  CREATE UNIQUE INDEX "MOVIEJD"."SYS_C007015" ON "MOVIEJD"."MEMBER_TBL" ("MEMBER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table MEMBER_TBL
--------------------------------------------------------

  ALTER TABLE "MOVIEJD"."MEMBER_TBL" ADD PRIMARY KEY ("MEMBER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "MOVIEJD"."MEMBER_TBL" MODIFY ("MEMBER_NICKNAME" NOT NULL ENABLE);
  ALTER TABLE "MOVIEJD"."MEMBER_TBL" MODIFY ("MEMBER_EMAIL" NOT NULL ENABLE);
  ALTER TABLE "MOVIEJD"."MEMBER_TBL" MODIFY ("MEMBER_GENDER" NOT NULL ENABLE);
  ALTER TABLE "MOVIEJD"."MEMBER_TBL" MODIFY ("MEMBER_NAME" NOT NULL ENABLE);
  ALTER TABLE "MOVIEJD"."MEMBER_TBL" MODIFY ("MEMBER_PW" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table NOTICE_TBL
--------------------------------------------------------

  ALTER TABLE "MOVIEJD"."NOTICE_TBL" MODIFY ("NOTICE_CONTENT" NOT NULL ENABLE);
  ALTER TABLE "MOVIEJD"."NOTICE_TBL" MODIFY ("NOTICE_SUBJECT" NOT NULL ENABLE);
  ALTER TABLE "MOVIEJD"."NOTICE_TBL" MODIFY ("NOTICE_NO" NOT NULL ENABLE);
